package org.lappsgrid.services.lindat.api;

/**
 * A naming interface used to identify objects that can generate the
 * query string passed to the Lindat services.  The query string is
 * generated by the class's <code>toString()</code> method.
 */
public interface QueryParams
{
}
